### ISSUE TITLE
Creating a "live coding" section

### ISSUE THREAD

**Issue by choldgraf** [Reproducible-Science-Curriculum/organization-RR-Jupyter#17]
Hey all - I created a folder called `live` that currently has a sample output of what our final demo folder directory should look like. This should help instructors in re-creating this lesson for their own purposes etc. LMK what you think and feel free to make any edits. It also includes the original dirty gapminder dataset, though I expect that it'll exist someone else in the lesson contents as well.

**Comment by iamciera** [comment]
This lesson was dramatically shortened, no time for live coding.  Although I love live coding!
