### ISSUE TITLE
Section 05 - Conclusions

### ISSUE THREAD

**Issue by choldgraf** [Reproducible-Science-Curriculum/organization-RR-Jupyter#9]
https://github.com/Reproducible-Science-Curriculum/organization-RR-Jupyter/blob/gh-pages/_episodes/05-conclusion.md

- [x] Actually add content
- [ ] First pass of comments

**Comment by choldgraf** [comment]
Updated this episode, though currently it is not very long and mostly recaps what has already been covered. LMK and we can start iterating from here.

**Comment by iamciera** [comment]
This lesson was dramatically shortened and recaps exist in slides.
